### ISSUE TITLE
Add support for Xcode 13.3 and Swift 5.6

### ISSUE THREAD

**Issue by mman** [getsidetrack/action-xcodeproj-spm-update#2]
Leaving this here for a reference.

This package uses `macos-latest` image of github, which currently stands on macOS 11 and Xcode 13.2.1.

Xcode 13.2.1 generates a `Package.resolved` file `version: 1` because it uses Swift 5.5.

Xcode 13.3 generates a `Package.resolved` file `version: 2` because it uses Swift 5.6.

Thus running this action against a project being developed in Xcode 13.3 always generates a PR with `Package.resolved` completely changed back to version 1.

As far as I can see there is no easy workaround at this moment.

**Comment by Sherlouk** [comment]
Hi Martin,

Apologies for the delay in getting back to you, I haven't been watching this repo and so wasn't notified. I've left this so long I need to start thinking about Xcode 14 😂 

I'll try and take a look at this. We may add a new input which allows the user (you) to specify the Xcode version - this should be easily doable via the developer path environment variable and should, I believe, give you exactly what you need.

This is on my to do list.

**Comment by Sherlouk** [comment]
This should now be supported with version 0.2.0.

You simply need to provide the `xcodePath` input (documented in the README!)

Please re-open this issue if you face any more problems. Apologies for the delay one again!
