### ISSUE TITLE
Not working for Xcode workspaces

### ISSUE THREAD

**Issue by carlosnaguilera** [getsidetrack/action-xcodeproj-spm-update#4]
The action, as it is now, doesn't work for workspaces.

I understand the solution would be adding the option to set workspace name and scheme as input parameters.

I was able to make it work hardcoding workspace and scheme but I didn't know how to add them as parameters. I'm bad at shell scripts...

**Comment by Sherlouk** [comment]
Absolutely - this is on my list to add in the next batch of features which I will hopefully have done in the next couple of days.

**Comment by Sherlouk** [comment]
This should now be supported with version 0.2.0.

You simply need to provide the `workspace` and `scheme` input (documented in the README!)

Please re-open this issue if you face any more problems. Apologies for the delay one again!

**Comment by carlosnaguilera** [comment]
It works like a charm. Thank you very much!
